<script src="<?php echo $ruta; ?>assets/lib/jquery/jquery.min.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/lib/bootstrap/dist/js/bootstrap.bundle.min.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/js/app.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/lib/jquery.nestable/jquery.nestable.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/lib/moment.js/min/moment.min.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/lib/datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/lib/select2/js/select2.min.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/lib/select2/js/select2.full.min.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/lib/bootstrap-slider/bootstrap-slider.min.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/js/app-form-elements.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/lib/prettify/prettify.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/lib/select2/js/select2.min.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/lib/select2/js/select2.full.min.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/js/app-icons.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/lib/jquery.niftymodals/dist/jquery.niftymodals.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/lib/jquery.gritter/js/jquery.gritter.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/js/app-ui-notifications.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/lib/jquery.fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
<script src="<?php echo $ruta; ?>assets/js/app-page-calendar.js" type="text/javascript"></script>